name: number_trivia_mvvm
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mocktail: ^0.3.0
  # service locator
  get_it: ^7.6.0
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
  connectivity_plus: ^4.0.0
  http: ^0.13.6
  # Local cache
  shared_preferences: ^2.1.1
  # Value equality
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^7.0.1
  path_provider: ^2.0.11
  provider: ^6.0.5
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

